version: "2"

services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:v1.6.0
    container_name: tyk-dashboard
    environment:
      - TYK_DB_REDISHOST=tyk-redis
      - TYK_DB_MONGOURL=tyk-mongo:27017
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - tyk-redis
      - tyk-mongo
      - tyk-gateway
  tyk-gateway:
    image: tykio/tyk-gateway:v2.5.4
    container_name: tyk-gateway
    environment:
      - TYK_GW_COPROCESSOPTIONS_ENABLECOPROCESS=false
      - TYK_GW_STORAGE_HOST=tyk-redis
    ports:
      - 8080:8080
    depends_on:
      - tyk-redis
  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v0.5.1
    container_name: tyk-pump
    depends_on:
      - tyk-redis
      - tyk-mongo
      - tyk-gateway
  tyk-redis:
    image: redis:4.0.9-alpine
    container_name: tyk-redis
    ports:
      - "6379:6379"
    volumes:
      - tyk-redis-data:/data
  tyk-mongo:
    image: mongo:3.2
    container_name: tyk-mongo
    ports:
      - "27017:27017"
    volumes:
      - tyk-mongo-data:/data/db
    command: ["mongod", "--smallfiles"]

volumes:
  tyk-redis-data:
  tyk-mongo-data:
